# COO/ CSR 형식 

In [10]:
from scipy import sparse
import numpy as np

dense = np.array([[0,1,2],
                  [0,3,4],
                  [0,0,0],
                  [0,5,6]])

#0이 아닌 데이터 추출
non_zero_data = np.arange(1,7)
row_pos = [0,0,1,1,3,3]
col_pos = [1,2,1,2,1,2]

#COO형식으로 변환
sparse_coo = sparse.coo_matrix((non_zero_data,(row_pos,col_pos)))
print('COO :\n',sparse_coo.toarray())

#행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_pos_ind = [0,2,4,4,6]

sparse_csr = sparse.csr_matrix((non_zero_data,col_pos, row_pos_ind))
print('CSR :\n',sparse_csr.toarray())


COO :
 [[0 1 2]
 [0 3 4]
 [0 0 0]
 [0 5 6]]
CSR :
 [[0 1 2]
 [0 3 4]
 [0 0 0]
 [0 5 6]]
